version: 2
updates:
  # --- GitHub Actions (CI) ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci" # -> ci(deps): ...
      include: "scope" # adds "(deps)" or "(deps-dev)"
    groups:
      # Group all PATCH and MINOR updates into one PR
      ci-patch-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
      # NOTE: major updates are left ungrouped -> one PR per major bump

  # --- npm (build) ---
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build" # -> build(deps): ...
      include: "scope" # adds "(deps)" or "(deps-dev)"
    groups:
      # Group all PATCH updates into one PR
      npm-patch:
        patterns: ["*"]
        update-types: ["patch"]
      # Group all MINOR updates into one PR
      npm-minor:
        patterns: ["*"]
        update-types: ["minor"]
      # NOTE: major updates are left ungrouped -> one PR per major bump
