version: 2
updates:
  # --- GitHub Actions (CI) ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci" # -> ci(deps): ...
      include: "scope" # adds "(deps)" or "(deps-dev)"
    open-pull-requests-limit: 5
    groups:
      # Group all PATCH and MINOR updates into one PR
      ci-patch-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
      # NOTE: major updates are left ungrouped -> one PR per major bump

  # --- npm (build) ---
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build" # -> build(deps): ...
      include: "scope" # adds "(deps)" or "(deps-dev)"
    open-pull-requests-limit: 5
    ignore:
      # TypeScript - only allow patch updates (type safety for SDK consumers)
      - dependency-name: "typescript"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]

      # ESLint - only allow patch updates (avoid new rules breaking builds)
      - dependency-name: "eslint"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]

      # Prettier - only allow patch updates (formatting consistency)
      - dependency-name: "prettier"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]

      # @types/node - only allow patch updates (Node.js compatibility)
      - dependency-name: "@types/node"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]

      # Runtime dependencies - only allow patch updates (affects SDK consumers)
      - dependency-name: "uuid"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "@types/uuid"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]

      # Build tools - only allow patch updates (affects SDK output)
      - dependency-name: "rollup"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "esbuild"
        update-types:
          ["version-update:semver-minor", "version-update:semver-major"]
    groups:
      # Test dependencies group
      test-dependencies:
        patterns:
          - "ava"
          - "@ava/*"
          - "sinon"
          - "@types/sinon"
          - "msw"
        update-types: ["patch", "minor", "major"]
      # Build dependencies - patch updates (auto-mergeable)
      build-patch:
        patterns: ["*"]
        exclude-patterns:
          - "ava"
          - "@ava/*"
          - "sinon"
          - "@types/sinon"
          - "msw"
        update-types: ["patch"]
      # Build dependencies - minor updates (requires review)
      build-minor:
        patterns: ["*"]
        exclude-patterns:
          - "ava"
          - "@ava/*"
          - "sinon"
          - "@types/sinon"
          - "msw"
        update-types: ["minor"]
      # Build dependencies - major updates (requires careful review)
      # Excludes test deps (which get major updates) and critical deps (which are blocked via ignore)
      # NOTE: critical dependencies (typescript, eslint, prettier, @types/node, uuid, @types/uuid, rollup, esbuild) have major/minor updates ignored
      build-major:
        patterns: ["*"]
        exclude-patterns:
          - "ava"
          - "@ava/*"
          - "sinon"
          - "@types/sinon"
          - "msw"
          - "typescript"
          - "eslint"
          - "prettier"
          - "@types/node"
          - "uuid"
          - "@types/uuid"
          - "rollup"
          - "esbuild"
        update-types: ["major"]
