name: e2e

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      E2E_API_ENDPOINT:
        required: true
      E2E_SCHEME:
        required: false # Optional, defaults to 'https'
      E2E_CLIENT_API_KEY:
        required: true
      E2E_SERVER_API_KEY:
        required: true
      NPM_TOKEN:
        required: true

env:
  NODE_VERSION: 20
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  e2e:
    name: e2e test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Init
        run: make init
      - name: Build
        run: make build
      - name: e2e test
        run: |
          echo "API_ENDPOINT=${{ secrets.E2E_API_ENDPOINT }}" > .env
          echo "SCHEME=${{ secrets.E2E_SCHEME || 'https' }}" >> .env
          echo "CLIENT_API_KEY=${{ secrets.E2E_CLIENT_API_KEY }}" >> .env
          echo "SERVER_API_KEY=${{ secrets.E2E_SERVER_API_KEY }}" >> .env
          make e2e
